### ISSUE TITLE
Push fail when using customized Dockerfile file name

### ISSUE THREAD

**Issue by thangma** [gonuit/heroku-docker-deploy#6]
Hi,
Please help to resolve the issue when I use a customized Dockerfile file name.
![image](https://user-images.githubusercontent.com/1381058/109469458-a0704380-7aa0-11eb-9827-5970dccd78f7.png)

**Comment by gonuit** [comment]
Hi @thangma 👋🏻,

Thank you for opening this issue. The error should be resolved in version `1.3.2`.
Let me know if this works for you.

**Comment by niteco-thangmai** [comment]
Hi @gonuit ,
Thank you for your quick response! but it still does not work for me. Please see detail in the screenshots.
![Screenshot_1](https://user-images.githubusercontent.com/17897729/109791954-96d41080-7c45-11eb-80ac-a30661717947.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/17897729/109791965-99366a80-7c45-11eb-9168-4180153a839c.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/17897729/109791976-9b002e00-7c45-11eb-9be1-26918d40b1e9.jpg)

**Comment by gonuit** [comment]
Hi @niteco-thangmai,
Let me know if version `1.3.3` resolves your issue.

**Comment by niteco-thangmai** [comment]
Hi @gonuit ,
Thank you for your quick fix! It works well with custom dockerfile name.
![image](https://user-images.githubusercontent.com/17897729/109903644-9df33100-7cce-11eb-9e11-f43dd3eda8c3.png)
